# User config
author: "Ksenia Bataeva"
tagline: "kclo"
whoami: "Data enthusiast"
tesis: "Data Analyst with software engineering background"
description: ""
keywords: "kclo"
email: "kclosu@gmail.com"
# linkedin: "https://www.linkedin.com/"
# twitter: "https://twitter.com/"
github: "https://github.com/kclosu"
telegram: "https://t.me/kclosu"

# Site config
url: "https://kclosu.github.io"
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
collections:
  projects:
    output: true
    permalink: /:collection/:name
